"""empty message

Revision ID: e870d042d291
Revises: af716fe3485f
Create Date: 2023-07-28 18:42:11.901717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e870d042d291'
down_revision = 'af716fe3485f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_memos_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memos_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
